describe('Cadastro de Usuários', () => {

    //Cenário 1
    it('Cadastro de Novo Usuário com Dados Válidos', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').type('lucas')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
    })

    //Cenário 2
    it('Validação de Campos Obrigatórios - Sem Nome e campos em branco', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').clear()
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').clear()
        cy.get('#new-email').clear()
        cy.get('#phone').clear()
        cy.get('.bg-body-tertiary > form > .btn').click()
    })

    //Cenário 3
    it('Validação de Formato de Dados - Email e Telefone Inválidos', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').type('lucas')
        cy.get('#new-email').type('lucasfabri.gmail.com.com.br')
        cy.get('#phone').type('lucasfabri')
        cy.get('.bg-body-tertiary > form > .btn').click()
    })

    //Cenário 4
    it('Pesquisa de Usuários', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').type('lucas')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').type('{selectall}{backspace}')
        cy.get('#name').type('fabri')
        cy.get('#new-email').type('{selectall}{backspace}')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('{selectall}{backspace}')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').type('{selectall}{backspace}')
        cy.get('#name').type('bernardo')
        cy.get('#new-email').type('{selectall}{backspace}')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('{selectall}{backspace}')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#filter').type('lucas')

    })

    //Cenário 5
    it('Ações na Lista de Usuários - Deletar Usuário', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').type('lucas')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').type('{selectall}{backspace}')
        cy.get('#name').type('fabri')
        cy.get('#new-email').type('{selectall}{backspace}')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('{selectall}{backspace}')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get(':nth-child(1) > :nth-child(4) > .btn-danger').click()
        cy.get(':nth-child(2) > :nth-child(4) > .btn-danger').click()
    })
    
    //Cenário 6
    it('Verificar Função Deslogar', () => {
        cy.visit('https://staging.d2pnv8jp5au9a7.amplifyapp.com/')
        cy.get('[data-test="email"]').type('admin@teste.com')
        cy.get('[data-test="password"]').type('123456')
        cy.get('[data-test="submit"]').click()
        cy.get('#name').type('lucas')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').type('{selectall}{backspace}')
        cy.get('#name').type('fabri')
        cy.get('#new-email').type('{selectall}{backspace}')
        cy.get('#new-email').type('lucasfabri.gt@gmail.com')
        cy.get('#phone').type('{selectall}{backspace}')
        cy.get('#phone').type('21974503489')
        cy.get('.bg-body-tertiary > form > .btn').click()
        cy.get('#name').type('{selectall}{backspace}')
        cy.get('#new-email').type('{selectall}{backspace}')
        cy.get('#phone').type('{selectall}{backspace}')
        cy.get('.nav-link').click()
        cy.get('[data-test="submit"]').click()
    })
})